/*
 * generated by Xtext
 */
package org.consoli.customlexerexample.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.consoli.customlexerexample.ui.internal.AttributesActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AttributesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AttributesActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AttributesActivator.getInstance().getInjector(AttributesActivator.ORG_CONSOLI_CUSTOMLEXEREXAMPLE_ATTRIBUTES);
	}
	
}
