/*
 * generated by Xtext
 */
package org.consoli.customlexerexample.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;


/**
 * Use this class to register components to be used within the IDE.
 */
public class AttributesUiModule extends org.consoli.customlexerexample.ui.AbstractAttributesUiModule {
	public AttributesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

}
