/**
 * generated by Xtext
 */
package org.consoli.customlexerexample.validation;

import org.consoli.customlexerexample.validation.AbstractAttributesValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class AttributesValidator extends AbstractAttributesValidator {
}
