/*
 * generated by Xtext
 */
package org.consoli.customlexerexample.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractAttributesValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.consoli.customlexerexample.attributes.AttributesPackage.eINSTANCE);
		return result;
	}
}
