/*
* generated by Xtext
*/
package org.consoli.customlexerexample;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AttributesStandaloneSetup extends AttributesStandaloneSetupGenerated{

	public static void doSetup() {
		new AttributesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

