/*
 * generated by Xtext
 */
package org.consoli.customlexerexample;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AttributesRuntimeModule extends org.consoli.customlexerexample.AbstractAttributesRuntimeModule {

}
