/*
* generated by Xtext
*/
package org.consoli.customlexerexample.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.consoli.customlexerexample.services.AttributesGrammarAccess;

public class AttributesParser extends AbstractContentAssistParser {
	
	@Inject
	private AttributesGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.consoli.customlexerexample.ui.contentassist.antlr.internal.InternalAttributesParser createParser() {
		org.consoli.customlexerexample.ui.contentassist.antlr.internal.InternalAttributesParser result = new org.consoli.customlexerexample.ui.contentassist.antlr.internal.InternalAttributesParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAttributeAccess().getAlternatives(), "rule__Attribute__Alternatives");
					put(grammarAccess.getSimpleAttributeAccess().getGroup(), "rule__SimpleAttribute__Group__0");
					put(grammarAccess.getArrayAttributeAccess().getGroup(), "rule__ArrayAttribute__Group__0");
					put(grammarAccess.getArrayAttributeAccess().getGroup_5(), "rule__ArrayAttribute__Group_5__0");
					put(grammarAccess.getModelAccess().getAttributesAssignment(), "rule__Model__AttributesAssignment");
					put(grammarAccess.getSimpleAttributeAccess().getNameAssignment_0(), "rule__SimpleAttribute__NameAssignment_0");
					put(grammarAccess.getSimpleAttributeAccess().getValueAssignment_1(), "rule__SimpleAttribute__ValueAssignment_1");
					put(grammarAccess.getArrayAttributeAccess().getNameAssignment_0(), "rule__ArrayAttribute__NameAssignment_0");
					put(grammarAccess.getArrayAttributeAccess().getItemsAssignment_4(), "rule__ArrayAttribute__ItemsAssignment_4");
					put(grammarAccess.getArrayAttributeAccess().getItemsAssignment_5_1(), "rule__ArrayAttribute__ItemsAssignment_5_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.consoli.customlexerexample.ui.contentassist.antlr.internal.InternalAttributesParser typedParser = (org.consoli.customlexerexample.ui.contentassist.antlr.internal.InternalAttributesParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public AttributesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AttributesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
