/*
* generated by Xtext
*/
package org.consoli.customlexerexample.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AttributesProposalProvider extends org.consoli.customlexerexample.ui.contentassist.AbstractAttributesProposalProvider {

}
