/**
 * generated by Xtext
 */
package org.consoli.customlexerexample.ui.contentassist;

import org.consoli.customlexerexample.ui.contentassist.AbstractAttributesProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class AttributesProposalProvider extends AbstractAttributesProposalProvider {
}
